import React from "react";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from 'sonner';

import { ThemeProvider } from "./themes/ThemeProvider";
import { LoadingProvider } from './loadingProvider/LoadingProvider';


import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartKitch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <LoadingProvider>
            <Toaster richColors position="bottom-center" />
            {children}
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
